# Generated by Django 2.1.5 on 2019-02-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
