# Generated by Django 2.1.5 on 2019-02-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_delete_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='active_lead',
            field=models.BooleanField(default=False),
        ),
    ]
